name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master
      - main

jobs:
  arkade-e2e:
    name: arkade-e2e
    runs-on: actuated-4cpu-4gb
    strategy:
      matrix:
        apps: [run-job,k3sup,arkade]
        #,arkade,kubectl,faas-cli]
    steps:
      - name: Get arkade
        run: |
          curl -sLS https://get.arkade.dev | sudo sh
      - name: Download app
        run: |
          echo ${{ matrix.apps }}
          sleep 30

